import type { MetadataRoute } from "next";

/**
 * Faz NOTIF.2C — PWA manifest, served at /manifest.webmanifest by Next's
 * App Router. The proxy matcher (proxy.ts) excludes any dotted path, so
 * this is delivered without i18n rewrite or session-refresh
 * interference.
 *
 * Colours are the actual SalonOS design-system tokens (app/globals.css):
 *   background_color  = --background (light)  oklch(0.99 0.004 75) -> #fdfbf9
 *   theme_color       = --primary (light)     oklch(0.42 0.07 195) -> #055959
 * No invented brand colours.
 *
 * Icons: static PNGs under public/icons/, cropped from the genuine
 * SalonOS gold emblem (emblem only — no wordmark/tagline). Generated by
 * scripts/generate-pwa-icons.mjs from public/brand/SalonOs_Logo.png; the
 * `maskable` purpose is on the dedicated maskable asset only. Dotted
 * paths, so proxy.ts' file rule already lets them through untouched.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "SalonOS",
    short_name: "SalonOS",
    description: "Kuaför ve güzellik salonları için operasyon platformu",
    lang: "tr",
    dir: "ltr",
    display: "standalone",
    orientation: "portrait",
    scope: "/",
    start_url: "/",
    id: "/",
    background_color: "#fdfbf9",
    theme_color: "#055959",
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icons/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
